# Generated by Django 6.0.6 on 2026-06-21 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=128, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_id', models.CharField(blank=True, max_length=128)),
                ('study_date', models.CharField(blank=True, max_length=32)),
                ('study_description', models.CharField(blank=True, max_length=255)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_studies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
