# Generated by Django 6.0.6 on 2026-09-08 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0003_segmentationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationjob',
            name='source_seg_sop_instance_uid',
            field=models.CharField(blank=True, help_text='SOP Instance UID of the AI-generated DICOM-SEG this job produced in Orthanc.', max_length=128),
        ),
        migrations.CreateModel(
            name='SegmentationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('accepted', 'Accepted as-is'), ('edited', 'Edited by reviewer'), ('rejected', 'Rejected')], max_length=16)),
                ('reviewed_seg_sop_instance_uid', models.CharField(blank=True, help_text='SOP Instance UID of the SEG instance stored back after this review (edited or re-stored).', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='worklist.segmentationjob')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
